version: 2
project_name: clustertool
builds:
  - id: clustertool
    dir: clustertool
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/truecharts/public/clustertool/main.version={{.Version}}  # Adjust path if necessary
archives:
  - name_template: "{{.ProjectName}}_{{ .Version }}_{{.Os}}_{{.Arch}}"
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^Merge pull request #\d+ from'
      - "^docs"
      - "^test"
    include:
      - "clustertool"
      - "clustertool"
      - "Clustertool"
release:
  name_template: "{{.ProjectName}}-{{.Tag}}"
  github:
    owner: truecharts
    name: public
  draft: true
  make_latest: false
  mode: append

git:
  ignore_tags:
    - nightly
    - common

universal_binaries:
  - replace: true

report_sizes: true

before:
  hooks:
    - chmod +x ./clustertool/partial_builds/partial_build.sh
    - bash ./clustertool/partial_builds/partial_build.sh
    - chmod +x ./clustertool/embed/download_talosctl.sh
    - bash ./clustertool/embed/download_talosctl.sh

sboms:
  - artifacts: archive
  -  id: source
     artifacts: source

nfpms:
  - id: clustertool-amd64
    package_name: clustertool
    builds:
      - amd64  # Reference to the amd64 build
    vendor: TrueCharts
    homepage: https://truecharts.org
    maintainer: "TrueCharts <info@truecharts.org>"
    description: "ClusterTool CLI for AMD64 architecture."
    license: BSL
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin
    contents:
      - src: ./dist/clustertool_linux_amd64_v1/clustertool
        dst: /usr/local/bin/clustertool

  - id: clustertool-arm64
    package_name: clustertool
    builds:
      - arm64  # Reference to the arm64 build
    vendor: TrueCharts
    homepage: https://truecharts.org
    maintainer: "TrueCharts <info@truecharts.org>"
    description: "ClusterTool CLI for ARM64 architecture."
    license: BSL
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin
    contents:
      - src: ./dist/clustertool_linux_arm64/clustertool
        dst: /usr/local/bin/clustertool
