---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate
  namespace: renovate
spec:
  interval: 10m
  chart:
    spec:
      chart: renovate
      version: 1.11.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    workload:
      main:
        schedule: "@hourly"
        podSpec:
          containers:
            main:

              env:
                GITHUB_COM_TOKEN: '${GITHUB_PAT}'
                # You can set RENOVATE_AUTODISCOVER to true to run Renovate on all repos you have push access to
                RENOVATE_AUTODISCOVER: 'false'
                RENOVATE_TOKEN: '${GITHUB_PAT}'
                RENOVATE_CONFIG_FILE: /tmp/renovate/config.json
                LOGLEVEL: debug

    configmap:
      config:
        enabled: false
