name: Automerge and Approve

on:
  workflow_run:
    workflows: ["Pull Request: Validate"]  # Name of the main CI workflow
    types:
      - completed

jobs:

  approve:
    runs-on: ubuntu-latest
    steps:
      - name: Approve PR
        uses: hmarr/auto-approve-action@v3
        if: ${{ 
          github.event.workflow_run.pull_requests[0].base.repo.id == github.event.workflow_run.pull_requests[0].head.repo.id && 
          (contains(github.event.workflow_run.head_commit.message, 'by renovate') || 
           contains(github.event.workflow_run.head_commit.message, '.all-contributorsrc'))
          }}
        with:
          github-token: "${{ secrets.OR_PAT }}"

  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Automerge
        uses: pascalgn/automerge-action@7961b8b5eec56cc088c140b56d864285eabd3f67 # v0.16.4
        env:
          GITHUB_TOKEN: "${{ secrets.BOT_TOKEN }}"
          UPDATE_RETRIES: 24
          UPDATE_RETRY_SLEEP: 60000
