name: "Pull Request: Validate"

on:
  pull_request:

concurrency:
  group: ${{ github.head_ref }}-pr-validate
  # cancel-in-progress: true

jobs:
  pr-changes:
    name: Collect PR changes
    runs-on: ubuntu-latest
    outputs:
      addedOrModified: ${{ steps.collect-changes.outputs.changesDetected }}
      addedOrModifiedFiles: ${{ steps.collect-changes.outputs.addedOrModifiedFiles }}
      addedOrModifiedCharts: ${{ steps.collect-changes.outputs.addedOrModifiedCharts }}
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Collect changes
        id: collect-changes
        uses: ./.github/actions/collect-changes

  containers-build:
    uses: ./.github/workflows/containers.build.yaml


  charts-lint:
    uses: ./.github/workflows/charts-lint.yaml
    needs:
      - pr-changes
    with:
      checkoutCommit: ${{ needs.charts-changelog.outputs.commitHash }}
      chartChangesDetected: ${{ needs.pr-changes.outputs.addedOrModified }}
      modifiedFiles: ${{ needs.pr-changes.outputs.addedOrModifiedFiles }}
      modifiedCharts: ${{ needs.pr-changes.outputs.addedOrModifiedCharts }}

  charts-test:
    uses: ./.github/workflows/charts-test.yaml
    needs:
      - pr-changes
      - charts-lint
    with:
      checkoutCommit: ${{ needs.charts-changelog.outputs.commitHash }}
      chartChangesDetected: ${{ needs.pr-changes.outputs.addedOrModified }}
      modifiedCharts: ${{ needs.pr-changes.outputs.addedOrModifiedCharts }}

  website-and-docs:
    uses: ./.github/workflows/charts-release.yaml
    needs:
      - pr-changes
      - charts-lint



  print_head_msg:
    name: Print commit message
    runs-on: ubuntu-latest
    outputs:
      head-commit-message: ${{ steps.get_head_commit_message.outputs.headCommitMsg }}
      pr-title: ${{ github.event.pull_request.title }}
    steps:
      - name: Get repo
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: verbose head git commit message
        run: echo "$(git show -s --format=%s)"
      - name: Print head git commit message
        id: get_head_commit_message
        run: echo "::set-output name=headCommitMsg::$(git show -s --format=%s)"
      - name: Print PR title
        run: |
          echo "PR title: ${{ github.event.pull_request.title }}"

  finished:
    needs:
      - pr-changes
      - containers-build
      - charts-lint
      - charts-test
      - website-and-docs
      - print_head_msg
    name: Finished PR Tests
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Finisher
        continue-on-error: true
        run: |
          echo "DONE"

  automerge-and-approve:
    needs:
      - finished
    if: ${{ 
      contains(needs.print_head_msg.outputs.head-commit-message, 'by renovate') || 
      contains(needs.print_head_msg.outputs.head-commit-message, '.all-contributorsrc') }}
    name: Automerge and Approve build
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: hmarr/auto-approve-action@v3
        continue-on-error: true
        with:
          github-token: "${{ secrets.OR_PAT }}"
      - name: automerge
        uses: pascalgn/automerge-action@7961b8b5eec56cc088c140b56d864285eabd3f67 # v0.16.4
        continue-on-error: true
        env:
          GITHUB_TOKEN: "${{ secrets.BOT_TOKEN }}"
          UPDATE_RETRIES: 24
          UPDATE_RETRY_SLEEP: 60000
          MERGE_METHOD: squash
